name: Build Eleventy
on: 
  push:
    paths-ignore:
      - README.md

jobs:
  build-deploy:
    name: Build Eleventy
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Build
        uses: TartanLlama/actions-eleventy@master
        with: 
          install_dependencies: true
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_dir: ./_site 
          github_token: ${{ secrets.GITHUB_TOKEN }}